version: '3.8'

services:
  redis:
    image: redis:7.2  # You can change to any desired Redis version
    container_name: redis-server
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: ["redis-server", "--appendonly", "yes"]
    restart: unless-stopped

volumes:
  redis-data:
