# .github/workflows/eslint.yml
name: ESLint

on: [push, pull_request]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install frontend dependencies
        run: cd frontend && npm ci
      - name: Run ESLint with flat config
        run: cd frontend && npx eslint . --ext .js,.jsx,.ts,.tsx

